version: '3.8'
services:
  node-app:
    build: 
      context: .
      target: production
      dockerfile: nodejs/Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
  flask:
    build: 
      context: .
      target: python-production
      dockerfile: Python/Dockerfile
    command:  python3.11 Flask/app.py
    # command: gunicorn -w 4 -b 0.0.0.0:6000 wsgi:Flask/app