version: '3.8'
services:
  node-app:
    container_name: voice-verse-app-container
    ports:
      - "3006:3006"
    env_file:
      - ./.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  flask:
    container_name: flask-container
    build:
      context: .
      dockerfile: Python/Dockerfile
      target: python-production  # Choose the target stage (python-development/python-production)
    ports:
      - "6000:6000"
#    command: python3.11 Flask/app.py
    volumes:
      - ./Flask:/app/Flask