version: '3.8'
services:
  node-app:
    container_name: voice-verse-app-container
    ports:
      - "3006:3006"
    env_file:
      - ./.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  django-app:
    #    build: .
    #
    container_name: django-app
    volumes:
      - static:/usr/src/app/static
      - .:/usr/src/app:rw
      - ./evenlabs:/usr/src/app:rw
    ports:
      - "8000:8000"
    env_file:
      - ./.env

#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis


volumes:
#    redisdata:
    static: