version: '3.8'
services:
  node-app:
    container_name: voice-verse-app-container
    ports:
      - "3006:3006"
    env_file:
      - ./.env
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  flask:
    # image: python3.11
    container_name: flask-container
    # ports:
    #   - "5000:5000"
    volumes:
      - Flask:/app/Flask
volumes:
  Flask: