version: '3.8'
services:
  node-app:
    build: 
      context: .
      dockerfile: nodejs/Dockerfile
      target: development
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev
  flask:
    command: python3.11 Flask/app.py