import os
from dotenv import load_dotenv

load_dotenv()

# EMAIL SETTINGS
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT", 587)
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
DEFAULT_SUPPORT_EMAIL = os.getenv("DEFAULT_SUPPORT_EMAIL")
DEFAULT_COMPANY_NAME = os.getenv("DEFAULT_COMPANY_NAME")
