version: "3.11"

services:
  django:
    build:
        context: .
        target: development
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/app:ro
    environment:
      - DJANGO_ENV=development
      - BASE_URL=http://localhost/
      - EMAIL_PORT= 587

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: development