version: "3.11"

services:
  django:
#    build: .
#
    container_name: django
    volumes:
      - static:/usr/src/app/static
    ports:
        - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
        - redis
  celery:
#    build:
#      context: .
#      target: production
    command: celery -A Core worker -l info
    container_name: celery
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    depends_on:
      - django
      - redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
        - ./nginx/snippets:/etc/nginx/snippets
        - ./nginx/ssl_certificate:/etc/nginx/ssl_certificate
        - ./nginx/proxy_params.conf:/etc/nginx/conf.d/proxy_params.conf
        - static:/usr/src/app/static
    depends_on:
        - django
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80

  redis:
    image: "redis:alpine"
    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data
volumes:
#    redisdata:
    static: