name: deploy-runner

on:
    push:
        branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          clean: false
      - name:  build docker image
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml -d up --build