name: deploy-runner

on:
    push:
        branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          clean: false
      - name:  Start voiceVerse-app.service
        run: |
          sudo systemctl restart voiceVerse-app.service